redhat-documentation/vale-at-red-hat

.vale/styles/Red-Hat-CCS/CheDocs/SentenceLength.yml

Removing CheDocs/SentenceLength.yml as it is a duplicate of IBM/SentenceLength.yml

Removing CheDocs/SentenceLength.yml as a duplicate

---

.vale/styles/Red-Hat-CCS/Vocab/RedHat/accept.txt

Adding backing and bindable. They appear to be legit words in OpenShift documentation.

Adding backing and bindable.

---

.github/workflows/build-and-validate-on-pr.yaml

Cache for Antora UI and Htmltest.
See: https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
Htmltest accepts 2 weeks old cache for the status code of checked external URLs
See: https://github.com/wjdp/htmltest
Refresh the cache every week to avoid a stale cache for htmltest
See: https://github.com/actions/cache
See: http://man7.org/linux/man-pages/man1/date.1.html

Fix cache for htmltest

---

.vale/styles/RedHat/shell-prompt.yml

A "shell" is a software application (for example, /bin/bash or /bin/sh) that provides an interface to a computer. Do not use this term to describe the prompt where you type commands.

fix: don't raise an error for 'shell'

---

.vale/styles/RedHat/Spelling.yml

To ease onboarding of new projects, set the alert level of the Spelling rule to warning rather than error. On new project it is expected that you need to adapt the Spelling rule to add new words in the dictionary (mostly products).

Set the alert level of the Spelling rule to warning rather than error

---

.vale/styles/RedHat/Spelling.yml

Add [dD]ev[wW]orkspace and Traefik to the Spelling rule.
Required for: https://github.com/eclipse/che-docs/pull/2125

feat: add [dD]ev[wW]orkspace and Traefik to the Spelling rule

---

.vale/styles/RedHat/ComplexWords.yml

Don't raise a warning for "Additional resources"

fix: remove warning on "additional"

---

.vale/styles/RedHat/Wordiness.yml

fixes #139 
Keep reference to 'refer to' only in the see.yml rule.
Remove it from Wordiness.yml.
It is already absent from Usage.yml, the issue is referring to an older version of the rule.

fix: #139 Duplicate rule: 'refer to'

---

.vale/styles/RedHat/ThereIs.yml

This rule originates from write-good. Sentences starting with There is are common in the Supplementary Style Guide.

fix: lower severity of the ThereIs rule

---

gulpfile.js

Necessary gulpfile.js update before publishing new che-docs container with Antora 3.0.0. See: https://github.com/eclipse/che-docs/pull/2213/
Antora 2.3 will enter maintenance on January 25, 2022 and reach end of life (EOL) on February 25, 2022. See: https://docs.antora.org/antora/latest/whats-new/#antora-2-3-eol

chore: prepare for Antora 3.0.0

---

.vale/fixtures/RedHat/TermsSuggestions/testinvalid.adoc
.vale/fixtures/RedHat/TermsSuggestions/testvalid.adoc
.vale/styles/RedHat/TermsSuggestions.yml

implements https://redhat-documentation.github.io/supplementary-style-guide/#text-entry
fixes #129

feat: input|type: enter (followed by the text to enter in monospace)

---

.github/workflows/vale-on-pull.yml
.github/workflows/vale-on-push.yml
modules/user-guide/pages/using-vale-github-action.adoc

* chore: https://github.com/errata-ai/vale-action  1.5.0 is out, let the worklows automatically pick the latest 1.x version
* chore: add onlyAnnotateModifiedLines: true

chore: allow using latest vale action

---

.github/workflows/release.yml
modules/user-guide/nav.adoc
modules/user-guide/pages/installing-vale-cli.adoc
modules/user-guide/pages/installing-vale-from-zip.adoc
tools/get-vale-styles-release.sh

This PR: 
* Adds version.txt to release zip
* Adds new procedure: how to install from release zip
* Adds new install from release zip script
partially addresses https://github.com/redhat-documentation/vale-at-red-hat/issues/211

Installing Vale from release zip

---

modules/user-guide/pages/installing-vale-from-zip.adoc

run -> enter (because we run scripts, but we enter or use commands)

Minor grammar fixes in installing-vale-from-zip.adoc

---

.vale/fixtures/RedHat/Slash/testvalid.adoc
.vale/styles/RedHat/Slash.yml

The IBM Style Guide explicitly allows N/A in situations where spelling
it out is impractical. It also explicitly recommends the use or
client/server and input/output with the slash so I added all of these to
the exceptions.
I realize that this style has ignorecase enabled but for some reason,
with vale 2.18.0, it still flagged Input/Output which is a very common
way of writing it in documentation. That is why I went ahead and used a
pattern match.

Do not report recommended terms in Slash

---

.vale/fixtures/RedHat/SimpleWords/testvalid.adoc
.vale/styles/RedHat/SimpleWords.yml

While it is difficult to reliably recognize a noun when defining vale rules, I run a quick search on Red Hat documentatiton and it looks like a few combinations are incredibely far more common than others. Consequently, I adapted the definition to avoid flagging these word combinations.

Do not suggest 'discuss' for 'address' used as a noun

---

.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/Spelling.yml

Both "backtrace" and "traceback" are valid terms in computing and used frequently when documenting debugging procedures. They are not listed flagged as incorrect in any of our style guides so I do not see a reason why they should be flagged by Vale as incorrect.

Do not flag "backtrace" and "traceback"

---

.vale/fixtures/RedHat/TermsSuggestions/testvalid.adoc
.vale/styles/RedHat/TermsSuggestions.yml

While the style guide does not explicitly states its opinion on using "such as" in product documentation, it uses it excessively throughout the Word usage section. As it is a common phrase, not ignoring it caused the term suggestion for "as" to generate too many misguided suggestions.

Do not flag "such as"

---

.vale/fixtures/RedHat/Usage/testvalid.adoc
.vale/styles/RedHat/Usage.yml

As per the style guide, both "virtual machine" and "machine learning" are permitted. This fix ensures that these valid uses of the word "machine", including variations such as "Java Virtual Machine", are no longer flagged.

Fix issue #209: Do not flag valid uses of "machine"

---

.vale/styles/RedHat/Slash.yml

The following warnings are false positives for IP address ranges in phrases like this:
```
an libvirt. For libvirt, the default is `192.168.126.0/24`.
|Optional. The IP address pools for services. The default is 172.30.0.0/16.
NOTE: IP networks are represented as strings using Classless Inter-Domain Routing (CIDR) notation with a traditional IP address or network number, followed by the "/" (slash) character, followed by a decimal value between 0 and 32 that describes the number of significant bits. For example, 10.0.0.0/16 represents IP addresses 10.0.0.0 through 10.0.255.255.
```
, which produce warnings like this:
```
238:13   warning  Use either 'or' or 'and' in     RedHat.Slash              
'0/14'                                                    
252:2    warning  Use correct …
```

Avoid false positives for IP address ranges that begin with "0/"

---

.vale/fixtures/RedHat/TermsSuggestions/testinvalid.adoc
.vale/styles/RedHat/TermsSuggestions.yml

IN the IBMSG, [navigate](https://www.ibm.com/docs/en/ibm-style?topic=word-usage) is a use with caution term. This PR adds navigate to the suggestions rule.
```
Use with caution navigate (verb)
Use only when a more direct verb, such as "click", "select", "browse", or "go to", is not applicable. Use only to provide direction to a location (for example, "Navigate to the directory that contains the files that you want to edit").
```

Add Navigate to Vale suggestion words

---

.vale/styles/RedHat/meta.json

This is a requirement to provide Red Hat as a Vale package based on
https://github.com/errata-ai/packages#requirements
fixes #252
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

Provide meta.json for styles

---

.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/Spelling.yml

The  `Spelling.yml` rules incorreclty issue a warning to use correct American English spelling for "SELinux". This fix prevents that.
There already are rules for correct spelling of SELinux in `CaseSensitiveTerms.yml` and `Headings.yml`.

Do not flag "SELinux" as invalid spelling

---

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/fixtures/RedHat/TermsErrors/testvalid.adoc
.vale/styles/RedHat/TermsErrors.yml

The IBM Style Guide prohibits the use of the word 'demon' to describe a program running in the background. This is a common typo in documentation though so Vale should warn about it.

Report the invalid use of 'demon' instead of 'daemon'

---

.vale/fixtures/RedHat/ConfigMap/testvalid.adoc
.vale/styles/RedHat/ConfigMap.yml

Closes #260
Adds a word boundary (\b) before "config" so that the ConfigMap
rule will not report as errors words or terms that end in
"config", for example, "kubeconfig".

Fixes ConfigMap reporting words ending in "config"

---

modules/user-guide/pages/using-vale-in-the-ide.adoc

Since Vale Server is deprecated, Vale CLI is the only option. The configuration field has been removed from the extension configuration UI.

feat: configuring the Vale Visual Studio Code extension is not required

---

.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/Headings.yml
.vale/styles/RedHat/Spelling.yml

The _**Spelling.yml**_ rules incorrectly warn that "productized" and "productize" are unknown words. 
This PR prevents a false-positive spelling suggestion for the words  "productized" and "productize". 
Note: These words are in the Oxford, Cambridge, Macmillian, and several other international dictionaries.

Do not flag "productized" or "productize" as invalid spelling

---

.vale.ini
modules/user-guide/pages/installing-vale-cli.adoc

The sample `.vale.ini `that is provided in the [Red Hat package and repo does](https://github.com/redhat-documentation/vale-at-red-hat/blob/main/.vale.ini) not mirror the recommended configuration of the following topic:
[Installing Vale with the RedHat package](https://redhat-documentation.github.io/vale-at-red-hat/docs/user-guide/installing-vale-cli/)

fix: Make vale.ini config sample match install doc

---

.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/Spelling.yml

Allowlist is a valid term: https://redhat-documentation.github.io/supplementary-style-guide/#user-interface-elements
It should not be caught in the spelling filter. This PR fixes this issue.

Spelling rules updates: Add 'allowlist' to spelling ignore list

---

.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/Spelling.yml

Example usage:
> Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete.

feat: add SLAs in the Spelling rule

---

.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/Spelling.yml

past tense of [proxy](https://www.merriam-webster.com/dictionary/proxy)
https://www.merriam-webster.com/dictionary/proxied
Example usage: 
> In workspaces that use the default Che-Theia IDE in a proxied environment, the *Workspace* panel might appear blank rather than showing available commands, terminals, and applications.

feat: add proxied to the Spelling rule

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml

Currently shows error `RedHat.CaseSensitiveTerms	Use 'YAML' rather than 'yaml'.` for the line 
.Example plugin.yaml
This check ensures that the check will only match `Yaml` and `yaml` when used as words.

Match only if YAML is used as a word

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/fixtures/RedHat/Headings/testvalid.adoc
.vale/fixtures/RedHat/Spelling/testinvalid.adoc
.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml
.vale/styles/RedHat/Headings.yml
.vale/styles/RedHat/Spelling.yml

The Spelling.yml and Heading.yml rules incorrectly detect spelling and capitalization issues with the open-source community project **RESTEasy**.
**RESTEasy** is a JBoss / Red Hat project that provides various frameworks to help you build RESTful Web Services and RESTful Java applications. **RESTEasy** is used in many Red Hat products, including products in the Runtimes portfolio. This PR prevents spelling and capitalization suggestion churn in the vale output.

feat: Add RESTEasy to spelling & capitalization

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/fixtures/RedHat/Spelling/testinvalid.adoc
.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml
.vale/styles/RedHat/Definitions.yml
.vale/styles/RedHat/Headings.yml
.vale/styles/RedHat/Spelling.yml

The following names/services/components are regularly used in Java programming documentation in the Software industry but flag as spelling or capitalization errors by the Red Hat Vale rules. 
- classloader & ClassLoader
- classpath
- ~~foobar~~
- GraalVM
- Hibernate ORM
- JUnit
- Kafka
- Mandrel
- MicroProfile
- MongoDB
- mutual TLS (and initialism: mTLS)
- OpenID Connect
- WebAuthn
This PR adds those proper nouns to the spelling, heading, and capitalization style rules.
**Fixes:**
Lots of false positives, particularly in Runtimes product docs, for example, **Red Hat build of Quarkus**.

Add common Java programming words to spelling & heading exceptions

---

.vale/fixtures/RedHat/UserReplacedValues/.vale.ini
.vale/fixtures/RedHat/UserReplacedValues/testinvalid.adoc
.vale/fixtures/RedHat/UserReplacedValues/testvalid.adoc
.vale/styles/RedHat/UserReplacedValues.yml
modules/reference-guide/nav.adoc
modules/reference-guide/pages/repeatedwords.adoc
modules/reference-guide/pages/userreplacedvalues.adoc

Implements a subset of https://redhat-documentation.github.io/supplementary-style-guide/#user-replaced-values. 
The rule uses the characteristics of user-replaced values (surrounded by brackets) to search for undesired hyphens.
The pull request also adds a missing documentation page for the `RepeatedWords` rule.
I chose the suggestion level as a starting alert level. It could be useful later to increase that level if the rule proves not to create false positives.

feat: underscores in user-defined values

---

modules/user-guide/pages/using-vale-github-action.adoc

Enhancements to the instructions for integrating Vale (& vale-at-red-hat style rules) into the workflow of a GitHub docs repo.
**Context:** I used the updated vale-actioninstructions in [#295](https://github.com/redhat-documentation/vale-at-red-hat/pull/295).

 feat: Enhancements to GH vale-actions documentation

---

.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/styles/RedHat/Spelling.yml
.vale/styles/RedHat/TermsErrors.yml

This PR fixes the following false flags in the vale-at-red-hat linter output:
RedHat.Spelling 7(292-305) Use correct American English spelling. Did you really mean 'Knowledgebase'?
❌ RedHat.TermsErrors 7(292-305) Use 'knowledge base' rather than 'Knowledgebase'.
**Why:**
The Red Hat supplementary style guide recommends the use of knowledgebase (without the space):
https://redhat-documentation.github.io/supplementary-style-guide/#rh-kb-links

fix: Remove 'knowledgebase' from TermErrors

---

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/fixtures/RedHat/TermsErrors/testvalid.adoc
.vale/fixtures/RedHat/TermsWarnings/testinvalid.adoc
.vale/fixtures/RedHat/TermsWarnings/testvalid.adoc
.vale/styles/RedHat/TermsErrors.yml
.vale/styles/RedHat/TermsWarnings.yml

removed 'on-premise' from termserrors
'on site' is now listed as a warning
fixed #198

removed 'on-premise' from termserrors

---

.vale/fixtures/RedHat/SelfReferentialText/.vale.ini
.vale/fixtures/RedHat/SelfReferentialText/testinvalid.adoc
.vale/styles/RedHat/SelfReferentialText.yml
modules/reference-guide/nav.adoc
modules/reference-guide/pages/selfreferentialtext.adoc

In the chapter about audience and medium, the IBM Style Guides recommends to avoid self-referential text like "this chapter" or "this topic" as much as possible. As this is particularly problematic in modular documentation where such text can theoretically appear anywhere in the document hierarchy, I added a vale style to report these as a suggestion.

Recommend to avoid self-referential text

---

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/fixtures/RedHat/TermsSuggestions/testinvalid.adoc
.vale/styles/RedHat/TermsErrors.yml
.vale/styles/RedHat/TermsSuggestions.yml

We currently list crash as an error term. This is incorrect. Crash in the verb form is incorrect, however, crash as a noun is acceptable in various usages. 
https://redhat-documentation.github.io/supplementary-style-guide/#crash
Demoting to Suggestion should fix for now. Ideally, we should catch with POS tagging only when crash is used as a verb. POS checking not possible with Vale rules - yet: https://github.com/errata-ai/vale-vscode/pull/60

Demoting crash from error to sugg

---

modules/user-guide/pages/installing-vale-cli.adoc

The Packages feature of Vale was introduced from v 2.16.0.
**Fixes:**
If a Vale user already has an older version of Vale installed when they run 'vale sync' as outlined in step 2 they will get an error.

Specify minimum Vale version needed for vale sync

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/fixtures/RedHat/RepeatedWords/testinvalid.adoc
.vale/fixtures/RedHat/RepeatedWords/testvalid.adoc
.vale/fixtures/RedHat/Spelling/testinvalid.adoc
.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml
.vale/styles/RedHat/Spelling.yml

Tests were broken, they are now fixed by updating the following:
* Added AsciiDoc and Asciidoctor to CaseSensitiveTerms, removed from spelling
* Fixed test fixture for repeated words

fix asciidoctor term error and error in repeated words test fextures

---

.vale/styles/RedHat/CaseSensitiveTerms.yml

This PR simplifies the regex to catch `Yaml`, `yaml`, but not `xyz.yaml`.

Simplify YAML regex

---

.vale/fixtures/RedHat/Usage/testinvalid.adoc
.vale/styles/RedHat/Usage.yml

CPU is an accepted term in the ISG and SSG and should not be flagged: https://www.ibm.com/docs/en/ibm-style?topic=word-usage#c

removing CPU from usage errors

---

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/fixtures/RedHat/TermsErrors/testvalid.adoc
.vale/fixtures/RedHat/TermsWarnings/testinvalid.adoc
.vale/fixtures/RedHat/TermsWarnings/testvalid.adoc
.vale/styles/RedHat/TermsErrors.yml
.vale/styles/RedHat/TermsWarnings.yml

"via" is an acceptable term in the IBM style guide in certain contexts and should be downgraded from an error.
Closes https://github.com/redhat-documentation/vale-at-red-hat/issues/324
Moving from error level to warning level.

Changing rule level for "via" from error to warning

---

.vale/styles/RedHat/TermsSuggestions.yml

Addresses #208.
I think the term 'by using' gets flagged incorrectly depending on the surrounding context. If you play around with the testvalid.adoc for termsuggestions, you can generate an incorrect error on 'by using'. 
See issue for more examples. I think it relates to what precedes the instance of 'by using'. Adding regex to allow anything before 'by' seems to fix this issue.

'By using' gets incorrectly flagged depending on the surrounding context

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/fixtures/RedHat/Spelling/testinvalid.adoc
.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml
.vale/styles/RedHat/Headings.yml
.vale/styles/RedHat/Spelling.yml

Reviewing https://github.com/redhat-documentation/vale-at-red-hat/pull/351, it seems like we should convert "JetBrains" from a Spelling rule to a CaseSensitiveTerms rule. WDYT?

[WIP] Convert JetBrains from a Spelling rule to a CaseSensitiveTerms rule?

---

.vale/fixtures/RedHat/Headings/testvalid.adoc
.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/Headings.yml
.vale/styles/RedHat/Spelling.yml

'Spotify' , 'GraphQL', and Quiltflower are valid spellings and should also be capitalized in body text and headings.
Both flag up as false positive orange warnings in Quarkus product docs by the spelling and heading rules.
This PR fixes that.

feat: Add Spotify, GraphQL, and Quiltflower to spelling & heading rules

---

.vale/styles/RedHat/RepeatedWords.yml

Add YAML delimiter (`---` line).
This is useful to concatenate all rules into a single YAML file for use with Grazie Professional on IntelliJ editors. See: https://plugins.jetbrains.com/plugin/16136-grazie-professional/docs/project-style-guides.html

chore: add YAML delimiter in all rules

---

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/fixtures/RedHat/TermsErrors/testvalid.adoc
.vale/fixtures/RedHat/TermsWarnings/testinvalid.adoc
.vale/fixtures/RedHat/TermsWarnings/testvalid.adoc
.vale/styles/RedHat/TermsErrors.yml
.vale/styles/RedHat/TermsWarnings.yml

The Red Hat Style Council recently revisited and updated the guidelines for using `plugin` and `plug-in` (noun & adjective forms) in Red Hat documentation, deviating from the ISG.
As per [RHSS issue 213](https://github.com/redhat-documentation/supplementary-style-guide/issues/213), `plugin` is  now the preferred form:
`Use "plugin" rather than "plug-in", unless you are updating existing content that uses the hyphenated form.`
This PR removes `plugin` from the Terms Errors rule and adds `plug-in` to the Terms Warnings rule.
This PR also removes the plural form, which was previously added to some of the rules/fixtures.

Remove plugin from disallowed term list

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml

etcd is a key-store that contains information for distributed systems or a cluster of machines. As illustrated in this sentence, it is never presented in uppercase, even at the beginning of a sentence. Currently, etcd is not documented in any of our guides, but will be submitted for consideration in the appropriate place for reference purposes.
Allowed: etcd
Not allowed: Etcd, ETCD, etcD, ETCd, and all other iterations of capitalization.

Add 'etcd' to case sensitive list

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/fixtures/RedHat/Spelling/testinvalid.adoc
.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml
.vale/styles/RedHat/Headings.yml
.vale/styles/RedHat/Spelling.yml

Updates to reduce the following false-positive orange warnings in the spelling, heading, and case-sensitive yml rulesets, which cause churn in the JAVA related developer documentation, especially within the Red Hat Runtimes products.
[aA]ccessor
[dD]eclaratively
[dD]ecompiler
[dD]eserialization
[hH]ardcoding
[mM]iddleware
[oO]verridable
[pP]preconfigured
[pP]prepend
[pP]prepended
[sS]erializer
[sS]erialization
[sS]erializable
[sS]ervlet
[tT]emplated
[vV]alidator
Agroal
AssertJ
BOM
BouncyCastle
Failsafe
Fernflower
Funqy
Jandex
Knowledgebase
Mockito
OpenJDK
PowerShell
Quarkiverse
Qute
WebSocket

Fix false positives in spelling and heading rules

---

.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/Spelling.yml

gh-387 adding a spelling exception for sysctl

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/fixtures/RedHat/Headings/testvalid.adoc
.vale/fixtures/RedHat/Spelling/testinvalid.adoc
.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml
.vale/styles/RedHat/Headings.yml
.vale/styles/RedHat/Spelling.yml

Fixes: The false positive spelling warning on content containing the proper noun 'Redis, which is a technology that is used by several Red Hat Runtimes products.
Reference: https://redis.io/

Add Redis to spelling, heading and case rules

---

.vale/fixtures/RedHat/TermsWarnings/testinvalid.adoc
.vale/styles/RedHat/TermsErrors.yml
.vale/styles/RedHat/TermsSuggestions.yml
.vale/styles/RedHat/TermsWarnings.yml
.vale/styles/RedHat/Usage.yml
modules/reference-guide/partials/ref_warning_terms.adoc

BIOS is a use with caution term since https://github.com/redhat-documentation/supplementary-style-guide/pull/250 got merged.

tidy up YML rules and adding BIOS to warning list

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/fixtures/RedHat/Headings/testvalid.adoc
.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/fixtures/RedHat/TermsSuggestions/testinvalid.adoc
.vale/fixtures/RedHat/TermsSuggestions/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml
.vale/styles/RedHat/Headings.yml
.vale/styles/RedHat/TermsErrors.yml
.vale/styles/RedHat/TermsSuggestions.yml

JAR is incorrectly flagged as an error against non-verb word usage in the vale report with the guidance:  "Use 'compress' or 'archive' rather than 'JAR'. 
In JAVA-related product docs, a task with lots of steps that include working with a JAR file, creates a lot of false-positive errors.
The style guideline for 'jar' relates to using jar/JAR as a verb, for example:
**To _jar_ something** :
This PR demotes the error to a suggestion and adds (verb) clarification. The PR also adds "JAR file" as a permitted exception.

Demote verb error on JAR to a warning

---

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/fixtures/RedHat/TermsErrors/testvalid.adoc
.vale/styles/RedHat/TermsErrors.yml

We should not use UPI or IPI acronyms in the docs according to the [SSG](https://redhat-documentation.github.io/supplementary-style-guide/). Instead use "installer-provisioned infrastructure" and "user-provisioned infrastructure". 
I am pretty certain the same goes for Assisted Installer although there is no official guidance. I opened an issue to follow up with that. I did check with the Assisted Installer writers and AI should be avoided - obvious confusion with artificial intelligence. I think it's pretty safe to add AI here too.

Adding rule to flag IPI, UPI and AI acronyms

---

.vale/styles/RedHat/PassiveVoice.yml

**Problem:**
The existing message that is presented when passive voice is detected suggests only one of the acceptable uses that our style guidelines call out. 
This PR adjusts the detail in the message to remove the detailed prerequisites guidance:

Enhance passive voice rule message.

---

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/fixtures/RedHat/TermsWarnings/testinvalid.adoc
.vale/fixtures/RedHat/Usage/testinvalid.adoc
.vale/styles/RedHat/TermsErrors.yml
.vale/styles/RedHat/TermsWarnings.yml
.vale/styles/RedHat/Usage.yml

In the Word Usage section, the IBM Style Guide recommends to avoid the use of word 'sane' as it might be offensive to neurodiverse people. As it provides alternatives, I added it to TermsWarnings to provide a warning.
In addition, the IBM Style Guide recommends to avoid using the phrases 'sanity check' and 'sanity test'. There already is a rule for 'sanity check' but for completeness and to honor the intent behind these recommendations, I added a warning for 'sanity test' and 'sanity' as well.

Add a warning for words 'sane' and 'sanity'

---

.vale/fixtures/RedHat/Usage/testinvalid.adoc
.vale/styles/RedHat/Usage.yml

I verified that the IBM Style does not have a guideline for "due to".

Remove "due to" fixes #417

---

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/fixtures/RedHat/TermsErrors/testvalid.adoc
.vale/styles/RedHat/TermsErrors.yml

An unfortunate typo sadly occasionally makes it to published documentation. Adding it to Vale increases author's chances of catching it early.

Ensure the correct spelling of OpenShift

---

.vale/fixtures/RedHat/Headings/testvalid.adoc
.vale/styles/RedHat/Headings.yml

* Added exceptions to the `RedHat.Headings` rule
* fixes https://github.com/redhat-documentation/vale-at-red-hat/issues/455
* unblocks https://github.com/containers/podman-desktop/pull/1541

feat: 'Podman Desktop' and 'Certificate Authorities (CA)' are correct in a title

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml

* fixes https://github.com/redhat-documentation/vale-at-red-hat/issues/458
* unblocks https://github.com/containers/podman-desktop/pull/1541

feat: 'Windows' is correct, it is not necessarly followed by 'Server'

---

.vale/fixtures/RedHat/PascalCamelCase/testinvalid.adoc
.vale/fixtures/RedHat/PascalCamelCase/testvalid.adoc
.vale/styles/RedHat/PascalCamelCase.yml

Turn off PascalCamel case rule in headings by using `scope: [list, sentence]` in the rule.

Turn off PascalCamel case rule in headings

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/fixtures/RedHat/PascalCamelCase/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml
.vale/styles/RedHat/PascalCamelCase.yml

"dedicated", "capsule", "central", "editor" words should not trigger the CaseSensitiveTerms.yml rule.

"dedicated", "capsule", "central", "editor" should not cause Vale errors

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml

Remove the `webservices|web services|Web Services: Web services` rule altogether. It is misleading outside of JBoss EAP docs.
Context: 
* https://redhat-internal.slack.com/archives/C04HKR61MN1/p1678368726101069
* https://redhat-internal.slack.com/archives/C0218RXJK5E/p1678354141706229

"Amazon Web Services" should not flag as an error term

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml

At the moment, Vale incorrectly reports the following error for any occurrence of "DM Multipath":
```
61:1  error  Use 'Directory Manager' rather  RedHat.CaseSensitiveTerms 
than 'DM'.
```
This is obviously problematic for Red Hat Enterprise Linux documentation that uses this term excessively. It is also potentially misleading because in this situation DM stands for "Device Mapper" so anyone following the advice would introduce a factual error in the documentation.

Do not report errors for DM Multipath

---

.vale/fixtures/RedHat/Spelling/testinvalid.adoc
.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/Spelling.yml

Since both "webview" and "Webview" are valid spellings, I removed the entry from SpellingErrors

removed webview/Webview from spelling errors

---

.vale/styles/RedHat/Abbreviations.yml
.vale/styles/RedHat/CaseSensitiveTerms.yml
.vale/styles/RedHat/Conjunctions.yml
.vale/styles/RedHat/ConsciousLanguage.yml
.vale/styles/RedHat/Contractions.yml
.vale/styles/RedHat/Definitions.yml
.vale/styles/RedHat/Ellipses.yml
.vale/styles/RedHat/HeadingPunctuation.yml
.vale/styles/RedHat/Headings.yml
.vale/styles/RedHat/OxfordComma.yml
.vale/styles/RedHat/PascalCamelCase.yml
.vale/styles/RedHat/PassiveVoice.yml
.vale/styles/RedHat/ReleaseNotes.yml
.vale/styles/RedHat/SelfReferentialText.yml
.vale/styles/RedHat/SentenceLength.yml
.vale/styles/RedHat/SimpleWords.yml
.vale/styles/RedHat/Slash.yml
.vale/styles/RedHat/Spacing.yml
.vale/styles/RedHat/Spelling.yml
.vale/styles/RedHat/TermsErrors.yml
.vale/styles/RedHat/TermsSuggestions.yml
.vale/styles/RedHat/TermsWarnings.yml
.vale/styles/RedHat/Usage.yml
.vale/styles/RedHat/UserReplacedValues.yml

* With Vale v2.24.1, unknown keys are now an error, see: https://github.com/errata-ai/vale/releases/tag/v2.24.1
* The `source` key is obsolete
Fixes errors:
```
+ vale modules/administration-guide/partials/proc_selecting-an-open-vsx-registry-instance.adoc modules/end-user-guide/partials/proc_setting-up-che-editor-yaml.adoc
E201 Invalid value [/projects/.vale/styles/RedHat/Abbreviations.yml:1:1]:
1* ---
2  extends: existence
3  level: error
1 error(s) decoding:
* '' has invalid keys: source
```
See: https://github.com/eclipse-che/che-docs/actions/runs/4628864466/jobs/8189824489

chore: compatibility with Vale 2.24.1

---

.github/workflows/preview-build.yml
.github/workflows/preview-deploy.yml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Updating workflows - save-state and set-output commands are deprecated

---

.vale/fixtures/RedHat/PascalCamelCase/testvalid.adoc
.vale/fixtures/RedHat/Usage/testinvalid.adoc
.vale/fixtures/RedHat/Usage/testvalid.adoc
.vale/styles/RedHat/PascalCamelCase.yml
.vale/styles/RedHat/Usage.yml

Per discussion in https://github.com/openshift/openshift-docs/pull/60604#issue-1727661831
- VMware is an allowed word, but was tripping the pascal case rule. Added an exception.
- ISG says not to use "machine" but we use it (validly) all the time, and I don't think that's specifically just OCP docs. Removed it from the usage list.

Adds VMware as pascal exception and allows "machine"

---

.vale/fixtures/AsciiDoc/ImageContainsAltText/.vale.ini
.vale/fixtures/AsciiDoc/LinkContainsLinkText/.vale.ini
.vale/fixtures/AsciiDoc/LinkContainsLinkText/testinvalid.adoc
.vale/fixtures/AsciiDoc/LinkContainsLinkText/testvalid.adoc
.vale/styles/AsciiDoc/LinkContainsLinkText.yml
modules/reference-guide/nav.adoc
modules/reference-guide/pages/images.adoc
modules/reference-guide/pages/links.adoc

Based on https://redhat-documentation.github.io/supplementary-style-guide/?topic=grammar-capitalization#cloud-services-links-hypertext
I added a rule that I hope flags empty link text and link text that only contains "click here" in a case insensitive way.
I also added pages for link text and images.

add rule for descriptive link text

---

.vale/fixtures/OpenShiftAsciiDoc/AdditionalResourcesHeadingHasRoleID/testinvalid.adoc
.vale/fixtures/OpenShiftAsciiDoc/AdditionalResourcesHeadingHasRoleID/testvalid.adoc
.vale/styles/OpenShiftAsciiDoc/AdditionalResourcesHeadingHasRoleID.yml

See here: https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#additional-resources-sections
This updates the Additional resources rule for assemblies to ensure it catches `== Additional resources` and `.Additional resources`. Dot formatting can be used in modules or assemblies. == format is used in assemblies only.

Accomodating `==` format headings for additional resources rule

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml

Enhances vale-at-red-hat rules as per recent CCS communication requesting that all instances of `Red Hat Java` are replaced with `Red Hat OpenJDK` or the full product name `Red Hat build of OpenJDK`.
Extract: 
"...always mention Red distribution of JDK as Red Hat OpenJDK.
Never use Red Hat Java in any content"
_**Note:** Not sure if the Red Hat `CaseSensitiveTerms.yml` rule is the right place for this but as per other similar Red Hat product name rules live here... I think these fall under a rule for product names as per @abhatt-rh's enhancement GH issue #530._

Add new Vale rule to catch instances of "Red Hat Java"

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/fixtures/RedHat/TermsErrors/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml
.vale/styles/RedHat/TermsErrors.yml

Further enhances the previously merged rule https://github.com/redhat-documentation/vale-at-red-hat/pull/578 following further Red Hat SME discussion about the guideline.
See also related Red Hat style PR [362](https://github.com/redhat-documentation/supplementary-style-guide/pull/362).

Follow on rule enhancement to #578

---

.vale/styles/RedHat/HeadingPunctuation.yml

Heading punctuation rule doesn't work. This PR fixes the rule.
This PR is a more manageable piece of this larger PR: https://github.com/redhat-documentation/vale-at-red-hat/pull/539

Fix heading punctuation rule

---

.vale/fixtures/RedHat/Spelling/testinvalid.adoc
.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/Spelling.yml

Fixes:
- False positive spelling warnings on Java-related software services/components/products/functions and some acceptable widely used programmatic terms encountered when running vale on Red Hat build of Quarkus docs.
- Removed some duplicate entries in spelling yml.
_Related heading rule enhancements to follow after this is merged._

Add fixes to reduce spelling rule false positives

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/fixtures/RedHat/Headings/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml
.vale/styles/RedHat/Headings.yml

This PR reduces false positives that come up regularly in Quarkus doc content.

Fix false positive churn flagged by the Headings and CaseSenstive rules

---

.vale/fixtures/RedHat/PascalCamelCase/testvalid.adoc
.vale/styles/RedHat/PascalCamelCase.yml

To reduce Vale noise. 
[OpenTelemetry](https://opentelemetry.io/) is the name of a collection of APIs, SDKs, and tools, and is becoming more popular in Runtimes doc content.

Add OpenTelemetry to the Pascal rule exceptions

---

.vale/fixtures/RedHat/TermsSuggestions/testinvalid.adoc
.vale/fixtures/RedHat/TermsSuggestions/testvalid.adoc
.vale/fixtures/RedHat/TermsWarnings/testinvalid.adoc
.vale/fixtures/RedHat/TermsWarnings/testvalid.adoc
.vale/styles/RedHat/TermsSuggestions.yml
.vale/styles/RedHat/TermsWarnings.yml

1. Corrects quick replace text
2. Removes CRUD from Warning rule since "CRUD" is caught by the Abbreviations rule
3. Removes a lot of Suggestion terms because these are now in the reworked Usage rule https://github.com/redhat-documentation/vale-at-red-hat/pull/585
This PR is a more manageable piece of this larger PR: https://github.com/redhat-documentation/vale-at-red-hat/pull/539

Clean up warnings and suggestions rule

---

.vale/fixtures/OpenShiftAsciiDoc/HardWrappedLines/testvalid.adoc
.vale/styles/OpenShiftAsciiDoc/HardWrappedLines.yml
tengo-rule-scripts/HardWrappedLines.tengo

DL lists with short explanations that don't take full stops should not trigger the hard-wrapped rule.
Eg., these are not complete sentence clauses and should not hit the rule
```asciidoc
Hard drive:: Permanent storage for operating system and/or user files that are used on a daily basis
RAM:: Temporarily stores information that the CPU uses during the math operation
```

Update hard wrapped rule to accomodate sentence clauses

---

.vale/fixtures/RedHat/TermsErrors/testvalid.adoc
.vale/styles/RedHat/TermsErrors.yml

The current implementation of `RedHat.TermsErrors` causes `vale` to report the following error for sentences like "you can configure meta options per alert agent as well as per recipient":
```
15:56   error       Use 'according to', 'as', or    RedHat.TermsErrors      
'as in' rather than 'as per'.
```
While "as well as" on its own is not recommended by the IBM Style Guide and gets reported by `RedHat.Usage`, the above error is out of place and the suggested wording is confusing.

Do not report 'as well as per something'

---

.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/Spelling.yml

Below is the list of Linux terms that are commonly used in Linux operating system documentation but are incorrectly regarded by `RedHat.Spelling` as errors. This produces an excessive number of false warnings in the documentation for Red Hat Enterprise Linux, in particular:
- 705× Kerberos
- 231× multipath
- 216× Stratis
- 126× ACLs
- 112× keytab
- 107× OSTree
- 54× Buildah
- 41× Skopeo
- ...
I went over the list of the most frequent false positives and tried to address them in this pull request.

Do not report common Linux terms

---

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/fixtures/RedHat/TermsErrors/testvalid.adoc
.vale/styles/RedHat/TermsErrors.yml

The current version of the IBM Style Guide does not prohibit the use of the word "laptop" in any way and recommends it to refer to mobile computer that is not a handheld device. On the contrary, the IBM Style Guide recommends to use the word "notebook" to refer only to an interface element that resembles a physical notebook with pages and tabs.
I am therefore proposing to remove this rule as it goes against what the style guide recommends.

Do not suggest to replace "laptop" with "notebook"

---

.vale/fixtures/OpenShiftAsciiDoc/HardWrappedLines/testvalid.adoc
.vale/styles/OpenShiftAsciiDoc/HardWrappedLines.yml
tengo-rule-scripts/HardWrappedLines.tengo

Code markup should not trip the hard wrapped line rule. 
```
`GET api/ocloudNotifications/v1/cluster/node/<node_name>/sync/ptp-status/lock-state/CurrentState`
```

Code markup should not trip the hard wrapped line rule

---

.vale/fixtures/AsciiDoc/ClosedIdQuotes/testinvalid.adoc
.vale/fixtures/AsciiDoc/ClosedIdQuotes/testvalid.adoc
.vale/styles/AsciiDoc/ClosedIdQuotes.yml

In addition to double quotes, AsciiDoc allows the use of single quotes around ID values, for example:
```
[id='some-name']
```
I extended the regular expression to report unclosed single-quote ID values as well as detect mismatched quotes:
```
[id='some-name]
[id='some-name"]
[id="some-name']
```

Detect problems in single-quote IDs

---

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/fixtures/RedHat/TermsErrors/testvalid.adoc
.vale/styles/RedHat/TermsErrors.yml

The IBM Style Guide strongly recommends using "Appendixes" instead of "Appendices". `RedHat.TermsErrors` already provides similar guidance for "matrices" and considering Red Hat documentation currently uses both variants in production, I think it would be valuable for Vale to start complaining about.

Write as shown: Appendixes

---

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/styles/RedHat/TermsErrors.yml

TermsErrors rule: 
```
'w/(?!o) ': "with "
'w/o': without
kilobytes?: KB|kB
```

A few updates to the Error terms

---

.vale/fixtures/RedHat/TermsSuggestions/testinvalid.adoc
.vale/fixtures/RedHat/TermsSuggestions/testvalid.adoc
.vale/styles/RedHat/TermsSuggestions.yml

Fixes https://github.com/redhat-documentation/vale-at-red-hat/issues/199.
SSG was finalized with regard to terminology for different architiectures. Adding this back into Vale rules as a suggestion.

Adding guidance for arch terms after SSG was updated

---

.vale/fixtures/RedHat/DoNotUseTerms/.vale.ini
.vale/fixtures/RedHat/DoNotUseTerms/testinvalid.adoc
.vale/fixtures/RedHat/DoNotUseTerms/testvalid.adoc
.vale/styles/RedHat/DoNotUseTerms.yml

Adding a "do not use" terms rule. Instead of suggesting text replacement, the swap field is used to provide inline context to the user regarding the specific term.
```terminal
$ vale .
testinvalid.adoc
1:1  suggestion  Do not use "please". Terms of   RedHat.DoNotUseTerms 
politeness are superfluous,                          
convey the wrong tone for                            
technical material, and are                          
not regarded the same way in                         
all cultures.                                        
```

Adding a "do not use" terms rule

---

.vale/fixtures/RedHat/TermsSuggestions/testvalid.adoc
.vale/styles/RedHat/TermsSuggestions.yml

This PR uses @jhradilek's changes from https://github.com/redhat-documentation/vale-at-red-hat/pull/366 Thanks @jhradilek :)
Came across this error in my own writing and figured it was important enough to get this in. There are some wrinkles with how Asciidoctor renders HTML, line breaks, paragraphs, etc that possibly affect how our text fixtures work but we can deal with that seperately IMO. It's a Vale bug.

Adding Jaromir's fix from #366

---

.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/Spelling.yml

Fixes https://github.com/redhat-documentation/vale-at-red-hat/issues/673

Add "reentrant" to spelling rule

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/fixtures/RedHat/Headings/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml

This PR makes a small correction to the style guidance rule for _role-based access control (RBAC)_.
This security term should be all lowercase (no capital _R_ in Role), unless at the start of a sentence, which is already detected and handled by vale-at-red-hat rules.

Fix heading and case-sensitive rule for role-based access control (RBAC)

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/fixtures/RedHat/Headings/testvalid.adoc
.vale/fixtures/RedHat/PascalCamelCase/testvalid.adoc
.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml
.vale/styles/RedHat/Headings.yml
.vale/styles/RedHat/PascalCamelCase.yml
.vale/styles/RedHat/Spelling.yml

This PR aims to reduce false positive heading warnings and adds guidance for capitalization in Red Hat style rules for the following names, which are commonly used in Red Hat Runtimes and developer products:
- Liquibase
- Mockito
- OpenTelemetry (OTel)
- OTel
- Temurin

Add valid component names to headings and capitalization rules

---

modules/user-guide/pages/using-vale-in-the-ide.adoc

The currently mentioned extension is deprecated and VS Code will suggest to use this newer extension.

Update recommended vale extension

---

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/fixtures/RedHat/TermsErrors/testvalid.adoc
.vale/styles/RedHat/TermsErrors.yml

Fixes #687 
New rule: Checks if there is a space before and a comma following "for instance". 
**question:** ❔ Should we also check for "for instance" with spaces before and after?

Added rule: for instance

---

modules/user-guide/pages/installing-vale-cli.adoc

I replaced a link to the deprecated vale-server extension with one for the newer _Vale VSCode_ extension.
Another topic, modules/user-guide/pages/using-vale-in-the-ide.adoc already links to the Vale VSCode extension.

Update with the URL of the new supported Vale VSCode extension

---

.vale/fixtures/RedHat/ProductCentricWriting/.vale.ini
.vale/fixtures/RedHat/ProductCentricWriting/testinvalid.adoc
.vale/styles/RedHat/ProductCentricWriting.yml
modules/reference-guide/pages/productcentricwriting.adoc

Based on this [How to put the customer first in your sentences](https://www.knowledgeowl.com/blog/posts/customer-first-in-your-sentences) article and a [slack message from Ingrid](https://redhat-internal.slack.com/archives/C04P5S34GP2/p1693151862297009), this rule flags "product-centric" sentence constructions suggesting that you rewrite the sentence in a more active and direct style.

Adding new product-centric writing rule

---

.vale/styles/OpenShiftAsciiDoc/AdditionalResourcesHeadingHasRoleID.yml
.vale/styles/OpenShiftAsciiDoc/IdHasContextVariable.yml
.vale/styles/OpenShiftAsciiDoc/ModuleContainsContentType.yml

Double quotes within the message body causes problems for further processing with other programs. For example, I get confused JSON converting to JSON
`{"body":"Module is missing the "_mod-docs-content-type" variable.","path":"test.adoc","line":1}`
Changing the 3 instances in the OCP rule set so it will read like the following, which is easier JSON to process.
` {"body":"Module is missing the '_mod-docs-content-type' variable.","path":"test.adoc","line":1}`
Using single quotes in messages is also the format used in other rule sets.

Replacing double quotes in alert messages with single quotes.

---

.vale/styles/AsciiDoc/SequentialNumberedCallouts.yml
.vale/styles/OpenShiftAsciiDoc/CheckDollarSymbolInTerminalBlock.yml
.vale/styles/OpenShiftAsciiDoc/HardWrappedLines.yml
.vale/styles/OpenShiftAsciiDoc/IdHasContextVariable.yml
.vale/styles/OpenShiftAsciiDoc/ModuleContainsContentType.yml
.vale/styles/RedHat/CaseSensitiveTerms.yml
.vale/styles/RedHat/ConsciousLanguage.yml
.vale/styles/RedHat/Hyphens.yml
.vale/styles/RedHat/ProductCentricWriting.yml
.vale/styles/RedHat/ReadabilityGrade.yml
.vale/styles/RedHat/UserReplacedValues.yml

1. Tightens what we fail as errors in RH Vale Styles
2. Adds quotes to errors messages where they are missing

Tightens what we fail as errors in RH Vale Styles

---

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/fixtures/RedHat/TermsErrors/testvalid.adoc
.vale/styles/RedHat/TermsErrors.yml

AI is more commonly understood to mean Artificial Intelligence, not Assisted Installer. This rule is misleading

remove AI from error terms

---

.vale/styles/AsciiDoc/MatchingDotCallouts.yml
.vale/styles/AsciiDoc/MatchingNumberedCallouts.yml
.vale/styles/AsciiDoc/SequentialNumberedCallouts.yml
.vale/styles/AsciiDoc/ValidAdmonitionBlocks.yml
.vale/styles/AsciiDoc/ValidCodeBlocks.yml
.vale/styles/AsciiDoc/ValidConditions.yml
.vale/styles/AsciiDoc/ValidTableBlocks.yml
.vale/styles/OpenShiftAsciiDoc/HardWrappedLines.yml
tengo-rule-scripts/HardWrappedLines.tengo
tengo-rule-scripts/MatchingDotCallouts.tengo
tengo-rule-scripts/MatchingNumberedCallouts.tengo
tengo-rule-scripts/SequentialNumberedCallouts.tengo
tengo-rule-scripts/ValidAdmonitionBlocks.tengo
tengo-rule-scripts/ValidCodeBlocks.tengo
tengo-rule-scripts/ValidConditions.tengo
tengo-rule-scripts/ValidTableBlocks.tengo

Since script rules operate on raw AsciiDoc (not HTML), the rules need to handle commented content explicitly.
This update cleans out the comments before linting the source file.
```
// clean out multi-line comments
scope = text.re_replace("(?s) *(\n////.*?////\n)", scope, "")
```

Clean out multi-line AsciiDoc comments in raw script rules

---

.vale/styles/AsciiDoc/ValidConditions.yml

Making it clearer that the user should search the entire file unbalanced if statements, not just the line where the alert is triggering.

Editing alert message as the line number of the alert may not be where the problem is

---

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/fixtures/RedHat/TermsWarnings/testinvalid.adoc
.vale/styles/RedHat/TermsErrors.yml
.vale/styles/RedHat/TermsWarnings.yml

"Carry out" is not an error term. 
https://www.ibm.com/docs/en/ibm-style?topic=word-usage#carry-out

demoting "carry out" to a warning

---

.vale/fixtures/RedHat/SimpleWords/testinvalid.adoc
.vale/styles/RedHat/SimpleWords.yml

Add utilizing to SimpleWords.yml
"utilize" and "utilization" are included in SimpleWords.yml but I think "utilizing" should also be added. 
Discussed in Vale Slack channel and I agreed to work on a PR.

Add utilizing to SimpleWords.yml

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml

Fixes incorrect flagging found in ocpdocs-vale-bot: https://github.com/openshift/openshift-docs/pull/72761#discussion_r1532155937

Allow for VT-d, the product is Intel VT-d so should be allowed

---

.vale/fixtures/RedHat/Spacing/testinvalid.adoc
.vale/fixtures/RedHat/Spacing/testvalid.adoc
.vale/styles/RedHat/Spacing.yml

In the CI, the spacing rule makes no sense. This update expands the regex to return a meaningful message.

Fix spacing rule 

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml

The SSG allows Azure as a term if it's already been defined previously as Microsoft Azure. So perhaps a more complex rule is required instead. 
Also too many errors on Azure product names.

Removing Azure as an error term 

---

modules/user-guide/nav.adoc
modules/user-guide/pages/installing-redhat-style-for-vale.adoc
modules/user-guide/pages/installing-vale-cli.adoc
modules/user-guide/pages/redhat-style-for-vale.adoc

Update the Installing section to highlight that installing Vale and creating/configuring `vale.ini` are two distinct procedures.

Clarifying docs

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml

Adding an exception for the term Kernel Module Management as this is a valid OCP operator. 
See false positive here: https://github.com/openshift/openshift-docs/pull/74713#discussion_r1567479450

Excluding term that is a valid OCP operator

---

.vale/fixtures/RedHat/EmDash/.vale.ini
.vale/fixtures/RedHat/EmDash/testinvalid.adoc
.vale/fixtures/RedHat/EmDash/testvalid.adoc
.vale/fixtures/RedHat/Hyphens/testvalid.adoc
.vale/styles/RedHat/EmDash.yml
modules/reference-guide/nav.adoc
modules/reference-guide/pages/emdashes.adoc

Do not use em dashes https://www.ibm.com/docs/en/ibm-style?topic=punctuation-dashes#em-dashes
Catches three forms:
1.  `—`
2. `&mdash;`
3. `(?<=\w)--(?=\w)`
`--` is AsciiDoc markup. See https://asciidoctor.org/docs/asciidoc-writers-guide/#replacements

Add an em dash rule

---

.vale/fixtures/RedHat/DoNotUseTerms/testvalid.adoc
.vale/styles/RedHat/DoNotUseTerms.yml

Builds on https://github.com/redhat-documentation/vale-at-red-hat/pull/780
`Red Hat` and `Red{nbsp}Hat` should not raise a Vale error.

Tweak Red Hat colours rule

---

.vale/fixtures/RedHat/TermsSuggestions/testvalid.adoc
.vale/styles/RedHat/TermsSuggestions.yml

Update "using" rule to accommodate these valid usages involving verbs, adverbs, prepositions, conjunctions, etc:
- are not using
- are using
- to using
- about using
- when using

Update using rule

---

.vale/fixtures/RedHat/SimpleWords/testinvalid.adoc
.vale/fixtures/RedHat/TermsWarnings/testinvalid.adoc
.vale/fixtures/RedHat/TermsWarnings/testvalid.adoc
.vale/styles/RedHat/SimpleWords.yml
.vale/styles/RedHat/TermsWarnings.yml

I was going through Applying the IBM Style Guide in Writing Product Documentation and checked to see if out rules had that info covered. 
- Also, we recommend using `accelerate` instead of speed up:

Added some phrasal verbs to avoid

---

.vale/styles/RedHat/Contractions.yml

``aren't`` was corrected to ``is not``. I changed the correction to ``are not``

Small Fix in Contractions.yml

---

.vale/fixtures/RedHat/PassiveVoice/testvalid.adoc
.vale/styles/RedHat/PassiveVoice.yml

```
exceptions:
- deprecated
- required
- imported
- supported
- trusted
- tested
```
~removed~ ~required~
Examples of the above terms in passive usage (lifted from openshift-docs):
1. Service Catalog is deprecated on {product-title} 4 and later.
2. When you create the virtual machine (VM), the data volume with the {object} is imported into persistent storage.
3. This credentials strategy is supported for only new {product-title} clusters and must be configured during installation.
4. Inject the CA bundle that is trusted by {product-title} into the config map by running the following command:
5. The default configuration used by DVM is tested in various environments.
~After the associated credential is removed, it can be deleted or deactivated on the underlying cloud.~
~If you deploy …

Add exceptions to the Passive voice rule

---

modules/user-guide/examples/gitlab-ci.yml
modules/user-guide/examples/vale-json.tmpl
modules/user-guide/pages/gitlab-code-quality-reports.adoc
modules/user-guide/pages/introduction.adoc

Previously, GitLab Vale code quality reports procedure was broken. This update fixes the docs and examples.
A complete working example is provided here: https://gitlab.cee.redhat.com/aireilly/asciidoc-vale-ci-demo/-/merge_requests/35

Update GitLab Vale code quality reports

---

.vale/fixtures/RedHat/PascalCamelCase/testvalid.adoc
.vale/styles/RedHat/PascalCamelCase.yml
.vale/styles/RedHat/Spelling.yml

Adding 'vCenter' to spelling rule

Add vCenter to Spelling rule

---

.vale/fixtures/RedHat/TermsErrors/testvalid.adoc
.vale/styles/RedHat/TermsErrors.yml

https://docs.openshift.com/container-platform/4.16/installing/installing_vsphere/ipi/ipi-vsphere-installation-reqs.html#installation-vsphere-installer-infra-requirements_ipi-vsphere-installation-reqs
vCenter datacenter is valid here

vCentre datacenter is an accepted term in OCP's VMWare implementation

---

.vale/styles/OpenShiftAsciiDoc/SuggestAttribute.yml

This change will cause the Vale bot in the OCP docs GH repo to leave comments when an attribute should be substituted. 
Note: this applies _only_ to attributes in the `SuggestAttribute.yml` file, not _all_ possible attributes to substitute. The intent is to ensure that some critical ones are noticed and used.
Per Shauna's observation, I have asked for input on clashes specifically for [MicroShift](https://redhat-internal.slack.com/archives/C85JYPHL3/p1719586566920439?thread_ts=1719585899.572939&cid=C85JYPHL3) and [SD docs](https://redhat-internal.slack.com/archives/C0308P3FC7R/p1719594945553029) use

upgrades attribute sub rule to error

---

.vale/styles/AsciiDoc/ImageContainsAltText.yml

If there are multiple entries in the raw array, they are concatenated into one large regular expression.  In this case, this meant that we were searching for the regular expression `image::.*\[\]image:.*\[\]`, which doesn't find images without alt text.
In this commit, we use a single regular expression that will match both cases: image with one colon, and image with two colons.
closes #829

Correct AsciiDoc.ImageContainsAltText criteria

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml

Removed "Red Hat Network Satellite Server" and "Red Hat Network Proxy Server" because these terms are obsolete.
Updated "Subscription manifest" because Satellite no longer capitalizes this term. (Maybe it should be just "Manifest: manifest"?)

Update Satellite terms

---

.vale/styles/RedHat/TermsErrors.yml

Trying to fix this error:
```
$ vale ${FILES} --minAlertLevel=warning --glob='*.adoc' --output="$(pwd)/vale-json.tmpl" > gl-code-quality-report.json
E201 Invalid value [/builds/telco-team-documentation/assisted-installer-saas-documentation/.vale/styles/RedHat/TermsErrors.yml:22:4]:
21    "(?<!self-)hosted engine|hosted-engine": self-hosted engine
22*   "bare metal( clusters?| compute| configuration| controls?| environments?| equipment| events?| hardware| hosts?| infrastructure| installations?| installers?| machines?| media| nodes?| provisioning| servers?| workers?)": bare-metal $1
23    "bare-metal(?! clusters?| compute| configuration| controls?| environments?| equipment| events?| hardware| hosts?| infrastructure| installations?| installers?| machines?| media| nodes?| provisioning| …
```

Fix 'bare metal' rule

---

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc

Deleting the 'bare metal' lines in the TermsErrors `testinvalid.adoc` file so that the rules validation check does not fail.

Remove 'bare metal' test lines

---

.vale/fixtures/RedHat/Hyphens/testinvalid.adoc
.vale/fixtures/RedHat/Hyphens/testvalid.adoc
.vale/styles/RedHat/Hyphens.yml

Add "re-register" (error) and "re-sign" (valid) to the hyphens rule.

Add "re-register" and "re-sign" to hyphens rule

---

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/styles/RedHat/TermsErrors.yml

We can put back the bare metal rule since the quay.io/rhdevdocs/devspaces-documentation container was updated.
```cmd
podman run quay.io/rhdevdocs/devspaces-documentation vale -v
vale version 3.7.0
```

Put back bare metal rule

---

.vale/fixtures/RedHat/PassiveVoice/testvalid.adoc
.vale/styles/RedHat/PassiveVoice.yml
.vale/styles/RedHat/TermsWarnings.yml

Add "is displayed" as valid exception and as alternative for "appears" per ISG usage.

Adding "is displayed"

---

.vale/fixtures/RedHat/TermsSuggestions/testinvalid.adoc
.vale/styles/RedHat/TermsSuggestions.yml

"Can not" is a do not use term in the ISG
https://www.ibm.com/docs/en/ibm-style?topic=word-usage#can-not

Remove dupe rule for cannot

---

.vale/fixtures/RedHat/Spelling/testvalid.adoc
.vale/styles/RedHat/Spelling.yml

Telco is a valid term per ISG: https://www.ibm.com/docs/en/ibm-style?topic=word-usage#telco

Adding telco spelling exception

---

.vale/fixtures/RedHat/ReadabilityGrade/testinvalid.adoc
.vale/fixtures/RedHat/ReadabilityGrade/testvalid.adoc
.vale/styles/RedHat/ReadabilityGrade.yml
modules/reference-guide/pages/readabilitygrade.adoc

The RedHat/ReadabilityGrade.yml rule is confusing. It's not clear how the grade level is calculated. This PR adds the rule with a suggested Flesch-Kincaid Grade Level value of < 9.

Implementing a Flesch–Kincaid grade level rule

---

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/fixtures/RedHat/TermsErrors/testvalid.adoc
.vale/styles/RedHat/TermsErrors.yml

Add "bare-metal instance" to valid list

Add bare-metal instance as valid

---

.vale/fixtures/OpenShiftAsciiDoc/ModuleContainsContentType/.vale.ini
.vale/fixtures/OpenShiftAsciiDoc/XrefMustNotHaveNakedLabel/.vale.ini
.vale/styles/OpenShiftAsciiDoc/ModuleContainsContentType.yml
.vale/styles/OpenShiftAsciiDoc/XrefMustNotHaveNakedLabel.yml

Expands on issue https://github.com/redhat-documentation/vale-at-red-hat/issues/867
**Analysis of remaining rules that are not at "error" status:**
* _AdditionalResourcesHeadingHasRoleID.yml:_ This doesn't break anything and is not actually used for anything in the build.
* _CheckDollarSymbolInTerminalBlock.yml:_ Too many false positives, suggest leaving it as is. Do not change.
* _HardWrappedLines.yml:_ Too many false positives. Do not change.
* _ModuleContainsContentType.yml:_ OK
* _ModuleContainsParentAssemblyComment.yml:_ this doesn't break anything and is not actually used for anything in the build. 
* _XrefMustNotHaveNakedLabel.yml:_ OK

vale-issue-867-expand: Bumped two OCP AsciiDoc rules to error status

---

.vale/fixtures/RedHat/GitLinks/.vale.ini
.vale/fixtures/RedHat/GitLinks/testinvalid.adoc
.vale/fixtures/RedHat/GitLinks/testvalid.adoc
.vale/styles/RedHat/GitLinks.yml

Closes https://github.com/redhat-documentation/vale-at-red-hat/issues/828

Add warning rule for Git links

---

.vale/fixtures/OpenShiftAsciiDoc/SuggestAttribute/testvalid.adoc
.vale/styles/OpenShiftAsciiDoc/SuggestAttribute.yml

Add "IBM Secure Execution" as an exception to the OpenShift attributes rule.

Add IBM Secure Execution exception

---

.vale/fixtures/OpenShiftAsciiDoc/SuggestAttribute/testvalid.adoc
.vale/styles/OpenShiftAsciiDoc/SuggestAttribute.yml

The rule that flags "IBM" is too simple and prone to false positives. In general, if a Vale rule is producing false positives, it's not fit for purpose and just adds noise and friction.
"When in doubt, leave it out" :smiley_cat:

Removing IBM suggested attribute rule

---

.vale/fixtures/AsciiDoc/SequentialNumberedCallouts/testvalid.adoc
.vale/styles/AsciiDoc/SequentialNumberedCallouts.yml
tengo-rule-scripts/SequentialNumberedCallouts.tengo

Based on the excellent work started in https://github.com/redhat-documentation/vale-at-red-hat/pull/827 (thanks @gaurav-nelson)
Updates the SequentialNumberedCallouts.yml rule to skip any callout blocks that include ifdefs.

Adding numbered sequential callout rule fix

---

.vale/fixtures/AsciiDoc/UnsetAttributes/.vale.ini
.vale/fixtures/AsciiDoc/UnsetAttributes/testinvalid.adoc
.vale/fixtures/AsciiDoc/UnsetAttributes/testvalid.adoc
.vale/styles/AsciiDoc/UnsetAttributes.yml
tengo-rule-scripts/UnsetAttributes.tengo

Adds a new AsciiDoc rule that highlights when an attribute is not unset in the same file. 
The rule fires for an attribute that is not unset in the file.

Adding unset attribute rule

---

.vale/fixtures/OpenShiftAsciiDoc/NoOptionalTitles/.vale.ini
.vale/fixtures/OpenShiftAsciiDoc/NoOptionalTitles/testinvalid.adoc
.vale/fixtures/OpenShiftAsciiDoc/NoOptionalTitles/testvalid.adoc
.vale/styles/OpenShiftAsciiDoc/NoOptionalTitles.yml

Add an OpenShiftAsciiDoc rule that flags "Optional:" in titles as an error.

Add OpenShift "No 'Optional:' titles" rule

---

.vale/fixtures/RedHat/TermsWarnings/testinvalid.adoc
.vale/styles/RedHat/TermsWarnings.yml

[ISG](https://www.ibm.com/docs/en/ibm-style?topic=elements-ui#menu) says not to use "vertical ellipsis" for the stacked dots menu (aka kebab menu).

Add "vertical ellipsis" to TermsWarnings

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml

https://redhat-documentation.github.io/supplementary-style-guide/#z-stream
"z-stream" and "y-stream" are lowercase compound hyphenated words.

Adding y-stream and z-stream terms

---

.vale/fixtures/RedHat/TermsWarnings/testinvalid.adoc
.vale/fixtures/RedHat/TermsWarnings/testvalid.adoc
.vale/styles/RedHat/TermsWarnings.yml

Because of the similarity of the two words, it is [not uncommon](https://docs.redhat.com/search/?p=1&rows=10&documentKind=Documentation&q=polices) to find the word 'police' or 'polices' used in place of 'policy' or 'policies'. As the former is highly unlikely to appear in software documentation, I propose to issue a warning when this word is found.

Warn when 'police' is used in place of 'policy'

---

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/styles/RedHat/TermsErrors.yml

Reverts redhat-documentation/vale-at-red-hat#903
Reverting because this rule is case insensitive. I want to prevent "Login to", not "login to". Personally, I think "login to" sounds awful but someone wrote "having a login to the cluster can help you ..."

Revert "Add "login to" error"

---

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc
.vale/styles/RedHat/CaseSensitiveTerms.yml
.vale/styles/RedHat/TermsErrors.yml

Add 'k8s' to TermsErrors.
Removed 'k8s' from CaseSensitiveTerms because the rule does not find 'K8s'.

Add 'k8s' to TermsErrors

---

.vale/styles/AsciiDoc/UnsetAttributes.yml

Since this is not technically an error at all for AsciiDoctor, and we allow our attributes to go unset generally, this rule does not need to be set to Warning.

Lowering error level for UnsetAttributes.yml

---

.vale/styles/RedHat/CaseSensitiveTerms.yml

AsciiDoc edge cases with setting attributes can cause Vale linting runs to fail on false positives. Dropping this error level to warning to ensure CIs pass the build.

Drop error level of CaseSensitiveTerms.yml

---

.vale/fixtures/OpenShiftAsciiDoc/TrailingBackslash/.vale.ini
.vale/fixtures/OpenShiftAsciiDoc/TrailingBackslash/testinvalid.adoc
.vale/fixtures/OpenShiftAsciiDoc/TrailingBackslash/testvalid.adoc
.vale/styles/OpenShiftAsciiDoc/TrailingBackslash.yml

Trailing backslashes in codeblocks break the openshift-docs Asciibinder build. Backslashes are only a problem in asciibinder when they come just before the end of a codeblock.

Adding trailing backslash rule

---

.vale/styles/RedHat/TermsErrors.yml

Add word boundary to "as per" rule to increase accuracy

Add word boundary to "as per" rule to increase accuracy

---

.vale/styles/RedHat/Spelling.yml
tools/validate-vale-rules.sh

By using regex word boundary (\b) delimiters, the spelling rule applies to individual words rather than a word that might contain the regex filter. For example, "\b[cC]he\b" will match only "che" and "Che" rather than a regex filter without word boundary delimiters, for example, "[cC]he" that would match misspelled words that contain the regex, such as "aache" or "chemitsry".
Closes #894

improve Spelling rule by using word boundaries

---

.vale/fixtures/RedHat/Using/testvalid.adoc
.vale/styles/RedHat/Using.yml

Nitpick improvement to the `Using.yml` style rule.
Fixes incorrect flagging of a word such as "focusing":
```
/vale_app/styles/RedHat # vale "Here is a rule focusing on clarity."
stdin.txt
1:11  warning  Use 'by using' instead of       RedHat.Using
'using' when it follows a noun
for clarity and grammatical
correctness.
✖ 0 errors, 1 warning and 0 suggestions in stdin.
```

improve Using style rule by using word boundaries

---

.vale/styles/RedHat/Slash.yml

"CI/CD" is a common concept promoted by Red Hat. See: https://www.redhat.com/en/topics/devops/what-is-ci-cd.

Add CI/CD exception to the Slash rule

---

.vale/styles/RedHat/Spelling.yml

Red Hat has a strong presence in bootc:
<https://github.com/bootc-dev/bootc/blob/main/MAINTAINERS.md#maintainers>.

fix: add bootc to RedHat.Spelling
