redhat-documentation/vale-at-red-hat

.vale/styles/Red-Hat-CCS/IBM/Usage.yml
fix: remove 'some'. Not present in IBM SG.
=> fix: remove 'some'. Not present in IBM SG.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/add-web-ide-link.yaml, .github/workflows/build-and-publish-to-github-pages.yaml, .github/workflows/build-and-validate-on-pr.yaml, .github/workflows/build-and-validate-on-push.yaml, .github/workflows/publish-netlify.yml, .github/workflows/release.yml, .github/workflows/vale.yml, .vale.ini, .vale/styles/RedHat/README-IBM.adoc, .vale/styles/RedHat/README-write-good.md, .vale/styles/RedHat/README.md, README.adoc, _config.yml, modules/end-user-guide/partials/proc_extending-the-spelling-rule.adoc, modules/end-user-guide/partials/proc_using-vale-github-action.adoc, red-hat.md
* Cleanup workflows.
* Fix remaining vale errors and workflows.
* Don't run vale on file path starting by a dot, to skip checks on the `testinvalid.adoc` files, which intentionally contain errors.
=> fix: cleanup workflows

.vale/fixtures/RedHat/Spelling/.vale.ini, .vale/styles/RedHat/Spelling.yml, modules/contributor-guide/partials/proc_extending-the-spelling-rule.adoc, modules/end-user-guide/partials/proc_generating-extended-vale-alerts-reports.adoc, tools/report_vale_alerts.sh
* Modify the Spelling rule
* Fix the procedure: Extending the Spelling rule
* Ignore some files in `tools/report_vale_alerts.sh`
=> New words in the Spelling rule

.vale.ini
Verified Rst now has Vale support addressing issue https://github.com/Vale-at-Red-Hat/vale-at-red-hat/issues/75
=> Enable RestructuredText in Vale

.github/workflows/pull-request-opened.yml
Add created pull requests to the project
=> Pull request opened triage

.vale/styles/RedHat/Spelling.yml
=> Update Spelling.yml - add Tekton

.gitignore, .vale.ini, modules/end-user-guide/partials/proc_generating-extended-vale-alerts-reports.adoc, tools/vale_report.sh
* Add a Spelling report.
* Rename `vale_report.sh`
* Fixes in `.vale.ini`
=> feat: Add a Spelling report.

.vale/styles/RedHat/Spelling.yml
Spelling entries. Mostly product names from devtools team.
=> feat: Spelling entries. Mostly product names from devtools team.

.vale/styles/RedHat/PassiveVoice.yml
=> feat: Allow passive voice in prerequisites 

.vale/styles/RedHat/Spelling.yml
fixes #119 Add [hH]ostname in the Spelling rule
=> fixes #119 Add [hH]ostname

.vale/fixtures/RedHat/ConsciousLanguage/.vale.ini, .vale/fixtures/RedHat/ConsciousLanguage/testinvalid.adoc, .vale/fixtures/RedHat/ConsciousLanguage/testvalid.adoc, .vale/styles/RedHat/ConsciousLanguage.yml
fixes https://github.com/Vale-at-Red-Hat/vale-at-red-hat/issues/124
*  See: https://redhat-documentation.github.io/supplementary-style-guide/#conscious-language
*  See: https://github.com/conscious-lang/conscious-lang-docs/blob/main/faq.md
=> feat: #124 Implement Conscious language rule.

.vale/styles/RedHat/Spelling.yml
Add "Use correct American English spelling" to the Spelling rule message.
=> docs: Use correct American English spelling

.vale/styles/RedHat/Spelling.yml
Add Dex to the Spelling rule (https://dexidp.io/).
=> feat: add Dex to the Spelling rule

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc, .vale/fixtures/RedHat/TermsErrors/testvalid.adoc, .vale/styles/RedHat/TermsErrors.yml
fix: #171 RedHat.TermErrors: plugin|plug in: plug-in
=> fix: #171 RedHat.TermErrors: plugin|plug in: plug-in

.github/workflows/build-and-publish-to-github-pages.yaml, .github/workflows/build-and-validate-on-pr.yaml, .github/workflows/build-and-validate-on-push.yaml, devfile.yaml, gulpfile.js, tools/runnerpreview.sh
chore: use the same container in every workflow 
chore: switch to container quay.io/antoraformodulardocs/antora-for-modular-docs:latest
fix: fixes broken publication due to a container not compatible with Antora 3
=> chore: use the same container in every workflow

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc, .vale/fixtures/RedHat/TermsErrors/testvalid.adoc, .vale/styles/RedHat/TermsErrors.yml
Also match plugins and plug ins
=> feat: TermErrors - plugin|plugins|plug in|plug ins: plug-in 

modules/user-guide/pages/adding-vale-configuration-to-a-project.adoc, modules/user-guide/pages/creating-a-vocabulary-for-a-project.adoc, modules/user-guide/pages/defining-a-vale-onboarding-strategy.adoc, modules/user-guide/pages/glossary.adoc, modules/user-guide/pages/installing-vale-cli.adoc, modules/user-guide/pages/introduction.adoc, modules/user-guide/pages/redhat-style-for-vale.adoc, modules/user-guide/pages/reporting-vale-alerts.adoc, modules/user-guide/pages/understanding-vale-output.adoc, modules/user-guide/pages/using-vale-github-action.adoc, modules/user-guide/pages/using-vale-in-the-ide.adoc, modules/user-guide/pages/using-vale-with-a-continuous-integration-service.adoc
adding aliases for old folder/files after rename
=> adding aliases for old folder/files after rename

.github/workflows/vale-on-pull.yml, .github/workflows/vale-on-push.yml, modules/user-guide/pages/using-vale-github-action.adoc
See:  errata-ai/vale-action#56
=> fix: Error: Unable to resolve action errata-ai/vale-action@v1, unable to find version v1

modules/contributor-guide/partials/ref_contributing.adoc
For clarity, add a link to a documentation explaining the  Git forking workflow.
=> docs: referencing Git forking workflow for clarity

modules/reference-guide/partials/ref_error_terms.adoc, modules/reference-guide/partials/ref_suggestion_terms.adoc, modules/reference-guide/partials/ref_warning_terms.adoc, tools/create-ssg-refs.py
This PR updates reference files and ssg python build script.
=> Updating reference files and ssg python build script

.vale/fixtures/RedHat/Headings/testvalid.adoc, .vale/fixtures/RedHat/Spelling/testinvalid.adoc, .vale/fixtures/RedHat/Spelling/testvalid.adoc, .vale/styles/RedHat/Headings.yml, .vale/styles/RedHat/Spelling.yml
feat: add Infinispan
fixes: https://github.com/redhat-documentation/vale-at-red-hat/issues/203
=> feat: add Infinispan

.vale/styles/RedHat/Spacing.yml
This PR corrects a typo in the Spacing.yml
This is my first itsy-bitsy PR for VaRH repo. Please let me know if I missed something. Thanks!
=> Correct a typo in the message for Spacing.yml

.vale/fixtures/RedHat/RepeatedWords/.vale.ini, .vale/fixtures/RedHat/RepeatedWords/testinvalid.adoc, .vale/fixtures/RedHat/RepeatedWords/testvalid.adoc, .vale/styles/RedHat/RepeatedWords.yml
Based on https://vale.sh/explorer/repeatedwords/
Matches instances of repeated words:
- This is is a sentence with a repeated word.
=> Added a new rule to check for repeated words rule

.vale/fixtures/RedHat/Spelling/testvalid.adoc, .vale/styles/RedHat/Spelling.yml
add JBoss to the Spelling rule
=> feat: add JBoss to the Spelling rule

.vale/styles/RedHat/Spelling.yml, modules/reference-guide/partials/ref_error_terms.adoc, tools/create-ssg-refs.py
`create-ssg-refs.py` refactor and adding missing SSG links to error reference page
TODO: Update error rules with latest SSG entries.
=> [WIP] create-ssg-refs.py refactor and adding missing SSG links to error reference page

.vale/styles/RedHat/Spelling.yml, modules/reference-guide/partials/ref_error_terms.adoc, tools/create-ssg-refs.py
Reverts redhat-documentation/vale-at-red-hat#221
=> Revert "[WIP] create-ssg-refs.py refactor and adding missing SSG links to error reference page"

modules/user-guide/pages/defining-a-vale-onboarding-strategy.adoc
Adapt to the changed destination link.
=> fix: changed link

.github/workflows/vale-on-pull.yml, modules/user-guide/pages/using-vale-github-action.adoc
fixes: https://github.com/redhat-documentation/vale-at-red-hat/issues/291
=> chore,docs: refresh Vale GitHub Action documentation and workflow

.vale/fixtures/RedHat/Spelling/testvalid.adoc, .vale/styles/RedHat/Spelling.yml, .vale/styles/RedHat/UserReplacedValues.yml
fixes https://github.com/redhat-documentation/vale-at-red-hat/issues/299
=> feat: underscores in user-defined values

.vale/styles/RedHat/ConfigMap.yml
Temporary workaround for https://github.com/redhat-documentation/vale-at-red-hat/issues/305
=> In ConfigMap.yml, demote level from `error` to `suggestion`

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc, .vale/styles/RedHat/TermsErrors.yml
Fixes https://github.com/redhat-documentation/vale-at-red-hat/issues/304
=> Remove "Use 'rather than' rather than 'instead of'."

.vale/fixtures/RedHat/Slash/testvalid.adoc, .vale/styles/RedHat/Slash.yml
added slash exception for C/C++
=> added slash exception for C/C++

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc, .vale/fixtures/RedHat/TermsErrors/testvalid.adoc, .vale/styles/RedHat/TermsErrors.yml
removed 'demo' from TermsErrors
fixes #311
=> removed 'demo' from termserrors

modules/user-guide/nav.adoc, modules/user-guide/pages/linting-vale-cli.adoc
Closes #255 
As a new user of Vale and the vale-at-red-hat style, I would like detailed instructions to help me to onboard and get started.
**Audience level:** Basic
This PR migrates a section of content in this [googledoc](https://docs.google.com/document/d/1S9jZc2EZ8vUm33t0rrTEr6FZH0WnOXEs7ajcbQIaqv0/edit#heading=h.vmqjqi81msm0), which was created and tested in a collaborative effort of the vale-at-red-hat team to enhance the onboarding experience.
=> Added user guide topic for linting your content by running Vale from the command line

.vale/fixtures/RedHat/RepeatedWords/testinvalid.adoc, .vale/fixtures/RedHat/RepeatedWords/testvalid.adoc, .vale/styles/RedHat/RepeatedWords.yml
=> Add a test invalid entry for a repeated word at the end of a sentence.

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/Spelling/testinvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml
Tidy up Mongo DB entries into one rule file - CaseSensitiveTerms.yml
=> Tidy up Mongo DB entries into one rule file - CaseSensitiveTerms.yml

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc, .vale/fixtures/RedHat/TermsErrors/testinvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml, .vale/styles/RedHat/TermsErrors.yml
Addresses https://github.com/redhat-documentation/vale-at-red-hat/issues/326
=> Don't fail on ConfigMap

.vale/fixtures/RedHat/TermsWarnings/testinvalid.adoc, .vale/fixtures/RedHat/TermsWarnings/testvalid.adoc, .vale/styles/RedHat/TermsWarnings.yml
"tooling" added to termswarning as per discussion in https://github.com/redhat-documentation/vale-at-red-hat/issues/313
=> "tooling" added to termswarning

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml
=> Fix incorrect product name flagged as an error

modules/contributor-guide/partials/con_vale-configuration-file.adoc, modules/contributor-guide/partials/proc_creating-a-vocabulary-for-a-project.adoc, modules/contributor-guide/partials/proc_extending-the-redhat-style.adoc, modules/contributor-guide/partials/proc_extending-the-spelling-rule.adoc, modules/contributor-guide/partials/ref_contributing.adoc, modules/reference-guide/pages/readabilitygrade.adoc, modules/user-guide/pages/adding-vale-configuration-to-a-project.adoc, modules/user-guide/pages/creating-a-vocabulary-for-a-project.adoc, modules/user-guide/pages/defining-a-vale-onboarding-strategy.adoc, modules/user-guide/pages/glossary.adoc, modules/user-guide/pages/using-vale-with-a-continuous-integration-service.adoc, modules/user-guide/partials/con_vale-command-line-tool.adoc, modules/user-guide/partials/con_vale-configuration-file.adoc, modules/user-guide/partials/con_vale-rule.adoc, modules/user-guide/partials/con_vale-style.adoc, modules/user-guide/partials/con_vale-vocabulary.adoc, modules/user-guide/partials/proc_adding-vale-configuration-to-a-project.adoc, modules/user-guide/partials/proc_creating-a-vocabulary-for-a-project.adoc, modules/user-guide/partials/proc_using-vale-on-a-local-environment.adoc, modules/user-guide/partials/proc_using-vale-with-a-continuous-integration-service.adoc, modules/user-guide/partials/ref_defining-a-vale-onboarding-strategy.adoc
Closes https://github.com/redhat-documentation/vale-at-red-hat/issues/293
=> Updated URLs to https://vale.sh/docs/

modules/contributor-guide/partials/proc_creating-a-vocabulary-for-a-project.adoc, modules/contributor-guide/partials/proc_extending-the-redhat-style.adoc, modules/contributor-guide/partials/proc_extending-the-spelling-rule.adoc, modules/user-guide/pages/adding-vale-configuration-to-a-project.adoc, modules/user-guide/pages/creating-a-vocabulary-for-a-project.adoc, modules/user-guide/pages/installing-vale-cli.adoc, modules/user-guide/pages/reporting-vale-alerts.adoc, modules/user-guide/pages/using-vale-cli.adoc, modules/user-guide/partials/proc_adding-vale-configuration-to-a-project.adoc, modules/user-guide/partials/proc_creating-a-vocabulary-for-a-project.adoc, modules/user-guide/partials/proc_generating-extended-vale-alerts-reports.adoc, modules/user-guide/partials/proc_using-vale-on-a-local-environment.adoc
Closes https://github.com/redhat-documentation/vale-at-red-hat/issues/266
=> Fix dollar sign in copied commands

antora.yml
Closes https://github.com/redhat-documentation/vale-at-red-hat/issues/347
=> Change `version` to main

modules/user-guide/pages/using-vale-app.adoc, modules/user-guide/pages/using-vale-cli.adoc
This PR includes some enhancements to the instructions for how to analyze your content by using the Vale app and the Vale command line options following an iteration of user testing by @kquinn1204.
=> Enhance'Analyzing' section of user guide as per test feedback

.vale/fixtures/RedHat/Spelling/testvalid.adoc, .vale/styles/RedHat/Spelling.yml
=> Fix issue #354: Add Keylime to RedHat.Spelling

.vale/styles/RedHat/Spelling.yml
=> fix broken links and tidy up - pt2

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc, .vale/fixtures/RedHat/TermsErrors/testvalid.adoc, .vale/fixtures/RedHat/TermsWarnings/testinvalid.adoc, .vale/fixtures/RedHat/TermsWarnings/testvalid.adoc, .vale/styles/RedHat/TermsErrors.yml, .vale/styles/RedHat/TermsWarnings.yml
updated termserrors and termswarning to match RH supplementary style guide
https://github.com/redhat-documentation/vale-at-red-hat/issues/317
=> RH supp style guide: termserrors update 

.vale/fixtures/RedHat/Spelling/testinvalid.adoc, .vale/fixtures/RedHat/Spelling/testvalid.adoc, .vale/styles/RedHat/Spelling.yml
Symfony: https://symfony.com/
sbt: https://www.scala-sbt.org/
=> feat: add Symfony, sbt to the Spelling rule

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc, .vale/fixtures/RedHat/TermsWarnings/testinvalid.adoc, .vale/styles/RedHat/TermsErrors.yml, .vale/styles/RedHat/TermsWarnings.yml
=> CRUD is registered as an error, which is blocking builds

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/Headings/testvalid.adoc, .vale/fixtures/RedHat/Spelling/testvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml, .vale/styles/RedHat/Headings.yml, .vale/styles/RedHat/Spelling.yml
feat: add Flathub, Flatpak, Podman Desktop
=> feat: add Flathub, Flatpak, Podman Desktop

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc, .vale/fixtures/RedHat/Headings/testvalid.adoc, .vale/fixtures/RedHat/TermsErrors/testinvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml, .vale/styles/RedHat/Headings.yml, .vale/styles/RedHat/TermsErrors.yml
=> Add rule for Basic authentication #407

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/Headings/testvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml, .vale/styles/RedHat/Headings.yml
Fixes https://github.com/redhat-documentation/vale-at-red-hat/issues/412
=> Add mTLS to Headings

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc, .vale/fixtures/RedHat/TermsErrors/testvalid.adoc, .vale/styles/RedHat/TermsErrors.yml
Fixes https://github.com/redhat-documentation/vale-at-red-hat/issues/441
=> Remove self-signed certificate from errors list

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc, .vale/fixtures/RedHat/TermsErrors/testvalid.adoc, .vale/styles/RedHat/TermsErrors.yml
"etc" should not be allowed, /etc in a folder path is OK:
1. /etc/
2. etc/
3. /etc
=> Refine rule for `etc` term

.vale/fixtures/RedHat/Spelling/testvalid.adoc, .vale/styles/RedHat/Spelling.yml
=> feat: 'desynchronize' and 'desynchronized' are correct

.vale/fixtures/RedHat/PascalCamelCase/testvalid.adoc, .vale/styles/RedHat/PascalCamelCase.yml
=> feat: 'PowerShell' is correct

.vale/fixtures/RedHat/Headings/testvalid.adoc, .vale/styles/RedHat/Headings.yml
=> feat: 'Technology Preview' is correct in a title

.vale/fixtures/RedHat/Headings/testvalid.adoc, .vale/styles/RedHat/Headings.yml
=> feat: 'Running Kind on Windows Subsystem for Linux' title is correct

.vale/fixtures/RedHat/Usage/testvalid.adoc, .vale/styles/RedHat/Usage.yml
=> feat: 'Podman machine' is correct

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc, .vale/fixtures/RedHat/TermsErrors/testinvalid.adoc, .vale/fixtures/RedHat/TermsErrors/testvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml, .vale/styles/RedHat/TermsErrors.yml
=> feat: 'Command Prompt' is correct, 'command prompt' is incorrect

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml
"GUI" term should not trigger a Vale error. 
Fixes https://github.com/redhat-documentation/vale-at-red-hat/issues/464
=> remove GUI error

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc, .vale/fixtures/RedHat/TermsSuggestions/testinvalid.adoc, .vale/fixtures/RedHat/TermsSuggestions/testvalid.adoc, .vale/styles/RedHat/TermsErrors.yml, .vale/styles/RedHat/TermsSuggestions.yml, modules/reference-guide/partials/ref_error_terms.adoc, modules/reference-guide/partials/ref_suggestion_terms.adoc
x86_64 should not be flagged as an error. Demoting to suggestion.
=> Move x86_64 to suggestion

.vale/styles/RedHat/Definitions.yml
`\b([A-Z]{3,5}s?)\b(?!\s\(([A-Z0-9][A-Za-z0-9]+\s?)+\))` explaination: https://regexr.com/79dip
=> Definitions.yml tweak

.vale/fixtures/RedHat/PascalCamelCase/testvalid.adoc, .vale/styles/RedHat/PascalCamelCase.yml
Adding GitHub, BitBucket, GitLab terms to PascalCamelCase.yml
=> add GitHub, BitBucket, GitLab terms

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/TermsSuggestions/testinvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml, .vale/styles/RedHat/TermsSuggestions.yml
Move "Router:AMQ Interconnect" from errors > suggestions
=> Remove "Router" from errors

.vale/fixtures/RedHat/PascalCamelCase/testvalid.adoc, .vale/styles/RedHat/PascalCamelCase.yml
=> fix: false positive for TypeScript

.vale/fixtures/RedHat/Spelling/testvalid.adoc, .vale/styles/RedHat/Spelling.yml
=> feat: Added Rollup and Webpack to the dictionary

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc, .vale/fixtures/RedHat/TermsErrors/testvalid.adoc, .vale/fixtures/RedHat/TermsSuggestions/testinvalid.adoc, .vale/fixtures/RedHat/TermsSuggestions/testvalid.adoc, .vale/styles/RedHat/TermsErrors.yml, .vale/styles/RedHat/TermsSuggestions.yml
downgraded "information on" from error to suggestion
based on https://github.com/redhat-documentation/vale-at-red-hat/issues/472
=> downgraded "information on" from error to suggestion

.vale/fixtures/RedHat/Spelling/testvalid.adoc, .vale/styles/RedHat/Spelling.yml
=> feat: added 'rootful' and 'rootless' to the Spelling rule

.vale/fixtures/RedHat/PascalCamelCase/testvalid.adoc, .vale/styles/RedHat/PascalCamelCase.yml
Add IntelliSense to PascalCamel case rule
=> Add IntelliSense to PascalCamel case rule

modules/user-guide/pages/installing-vale-cli.adoc
Fixes https://github.com/redhat-documentation/vale-at-red-hat/issues/510
=> Added prereqs to the installation topic

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc, .vale/fixtures/RedHat/Headings/testvalid.adoc, .vale/fixtures/RedHat/Spelling/testvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml, .vale/styles/RedHat/Headings.yml, .vale/styles/RedHat/Spelling.yml
Fixes https://github.com/redhat-documentation/vale-at-red-hat/issues/509
=> Add JBang terminology

.vale/styles/RedHat/collate-output.tmpl, modules/user-guide/nav.adoc, modules/user-guide/pages/collating-vale-output.adoc
Fixes https://github.com/redhat-documentation/vale-at-red-hat/issues/517
=> Add collate template

.vale/fixtures/RedHat/TermsSuggestions/testinvalid.adoc, .vale/fixtures/RedHat/TermsSuggestions/testvalid.adoc, .vale/styles/RedHat/TermsSuggestions.yml
Remove Cloud > cloud term suggestion - it's not useful
=> Remove Cloud > cloud term suggestion - it's not useful

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml
"operator" is a valid noun in logic, software and Boolean algebra contexts.
=> WIP - remove Operator rule

.vale/fixtures/RedHat/TermsSuggestions/testvalid.adoc, .vale/styles/RedHat/Spelling.yml
Hopefully I have done this correctly :crossed_fingers:
=> Adds Nutanix and VMware as valid words

.vale.ini, modules/user-guide/examples/vale.ini
=> updates vale.ini

.vale/fixtures/RedHat/OxfordComma/testinvalid.adoc, .vale/fixtures/RedHat/OxfordComma/testvalid.adoc, .vale/styles/RedHat/OxfordComma.yml
Fixes https://github.com/redhat-documentation/vale-at-red-hat/issues/541
=> Fix Oxford comma rule

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc, .vale/fixtures/RedHat/PascalCamelCase/testvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml, .vale/styles/RedHat/PascalCamelCase.yml
https://redhat-documentation.github.io/supplementary-style-guide/#o-ran
https://redhat-documentation.github.io/supplementary-style-guide/#openran
=> Adding RAN terms to rules and exceptions

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml
**I'll reopen this PR after Oct 1st. Please do not review this PR**
PR addresses Hacktoberfest issue #640
=> [hacktoberfest2023] issue-640: Add softirq to Vale at Red Hat rules

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml
=> Update case-sensitive terms rule in Red Hat style guide

.vale/fixtures/OpenShiftAsciiDoc/NoTocInModules/.vale.ini, .vale/fixtures/OpenShiftAsciiDoc/NoTocInModules/testinvalid.adoc, .vale/fixtures/OpenShiftAsciiDoc/NoTocInModules/testvalid.adoc, .vale/styles/OpenShiftAsciiDoc/NoTocInModules.yml
=> No TOC are allowed in OpenShift modules

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml
=> Added "DNF Automatic: case sensitive term rule

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml
=> Add rbac yml rule to the Red Hat style guide

.vale/styles/RedHat/TermsSuggestions.yml
This will close issue #514 
Happy Hacktoberfest!
=> Improve TermsSuggestions to not flag "By using"

.vale/fixtures/RedHat/Headings/testvalid.adoc
Related: https://github.com/redhat-documentation/vale-at-red-hat/issues/668
=> Commenting broken fixture

.vale/fixtures/RedHat/Spelling/testvalid.adoc, .vale/styles/RedHat/Spelling.yml
Fixes https://github.com/redhat-documentation/vale-at-red-hat/issues/581
=> Add deserialize and variants

modules/user-guide/pages/asciidoc-style-for-vale.adoc, modules/user-guide/pages/openshift-asciidoc-style-for-vale.adoc
=> 618: Fixing packages in VRH docs procedure

modules/user-guide/pages/installing-vale-cli.adoc
=> Update installation instructions

.vale/fixtures/AsciiDoc/ClosedAttributeBlocks/testinvalid.adoc, .vale/fixtures/AsciiDoc/ClosedAttributeBlocks/testvalid.adoc, .vale/fixtures/AsciiDoc/ClosedIdQuotes/testvalid.adoc, .vale/fixtures/OpenShiftAsciiDoc/HardWrappedLines/testvalid.adoc, .vale/fixtures/OpenShiftAsciiDoc/IdHasContextVariable/testvalid.adoc, .vale/fixtures/OpenShiftAsciiDoc/ModuleContainsContentType/testinvalid.adoc, .vale/fixtures/OpenShiftAsciiDoc/ModuleContainsContentType/testvalid.adoc, .vale/fixtures/OpenShiftAsciiDoc/NoTocInModules/testinvalid.adoc, .vale/fixtures/OpenShiftAsciiDoc/NoTocInModules/testvalid.adoc, .vale/styles/OpenShiftAsciiDoc/ModuleContainsContentType.yml, modules/user-guide/pages/openshift-asciidoc-style-for-vale.adoc
Fixes https://github.com/redhat-documentation/vale-at-red-hat/issues/679
We won't merge this PR until we get the go-ahead to do so from @kalexand-rh.
=> Replace the :_content-type: variable with the :_mod-docs-content-type: variable

modules/user-guide/pages/installing-vale-cli.adoc
https://redhat-documentation-vale-at-red-hat-706.surge.sh/docs/main/user-guide/installing-vale-cli/
=> Update install instructions for Fedora 39 CSB

tools/vale_report.sh
The script was accidentally removed some time back. 
https://github.com/themr0c/vale-at-red-hat/blob/4fbb775a522097f522740c01e9218a2b6c1ea23b/tools/vale_report.sh
=> Put back Fabrice's tools/vale_report.sh script

modules/user-guide/pages/using-vale-in-the-ide.adoc
=> Warn against duplicate Vale plugin for Visual Studio Code 

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc, .vale/styles/RedHat/TermsErrors.yml
Adding new SSG terms updates Feb 2024
opt into: opt in
opting into: opting in to
=> Adding new SSG terms updates Feb 2024

.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml
Azure Red Hat OpenShift is an officially approved short form Microsoft Azure Red Hat OpenShift.
https://azure.microsoft.com/en-us/products/openshift/
=> Adding exception for "Azure Red Hat OpenShift"

.vale/fixtures/RedHat/TermsSuggestions/testinvalid.adoc, .vale/fixtures/RedHat/TermsSuggestions/testvalid.adoc, .vale/styles/RedHat/TermsSuggestions.yml
https://redhat-documentation.github.io/supplementary-style-guide/#operator
=> Adding operator rule

.vale/fixtures/RedHat/SmartQuotes/.vale.ini, .vale/fixtures/RedHat/SmartQuotes/testinvalid.adoc, .vale/fixtures/RedHat/SmartQuotes/testvalid.adoc, .vale/styles/RedHat/SmartQuotes.yml, modules/reference-guide/nav.adoc, modules/reference-guide/pages/smart-quotation-marks.adoc
New rule to catch incorrect quotation mark characters in source
https://www.ibm.com/docs/en/ibm-style?topic=punctuation-quotation-marks#typographical-considerations
(thanks Sarah :partying_face:)
=> Adding smart quotation marks rule

modules/user-guide/pages/using-vale-app.adoc
Now that online app is deprecated, let's update the instructions. Thank you @aireilly
=> Updated using-vale-app.adoc

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml
Updating entry for "Customer Portal" Vale error
=> Updating entry for "Customer Portal" Vale error

.vale/styles/RedHat/DoNotUseTerms.yml
Updated link in DoNotUseTerms.yml style file
=> Fixes "Page not found" error for Do not use terms 

.vale/fixtures/AsciiDoc/ImageContainsAltText/testinvalid.adoc, .vale/fixtures/AsciiDoc/ImageContainsAltText/testvalid.adoc, .vale/styles/AsciiDoc/ImageContainsAltText.yml
I think this item needs an update to work with images that only have one colon.
=> image contains alt text update

.vale/fixtures/RedHat/TermsWarnings/testinvalid.adoc, .vale/styles/RedHat/TermsWarnings.yml
Add terms for The Hybrid Cloud Console
=> Add terms for The Hybrid Cloud Console

.vale/fixtures/AsciiDoc/ClosedAttributeBlocks/testvalid.adoc, .vale/styles/AsciiDoc/ClosedAttributeBlocks.yml
Don't flag JSON: 
```
[{    
JSON
}]
```
=> Adding attribute block fix

.vale/fixtures/RedHat/Spelling/testvalid.adoc, .vale/styles/RedHat/Spelling.yml
=> vale-issue-794: Add rulebook to Spelling.yml Red Hat style

.vale/styles/RedHat/TermsSuggestions.yml
=> on-premise-ocp-797

.vale/styles/RedHat/Spelling.yml
https://www.techtarget.com/searchstorage/definition/gibibyte-GiB
=> Add gibibyte to Spelling rule

.vale/styles/RedHat/Spelling.yml
Adding a less confusing Spelling rule error message
=> Adding new Spelling rule error message

.vale/styles/RedHat/TermsErrors.yml
Closes https://github.com/redhat-documentation/vale-at-red-hat/issues/791
=> Add "peer-pod" to TermsErrors.yml

.vale/fixtures/OpenShiftAsciiDoc/SuggestAttribute/testvalid.adoc, .vale/styles/OpenShiftAsciiDoc/SuggestAttribute.yml
This doesn't fix the RegEx I am trying to nail down, but it does update the Tempo Operator suggestion correctly
More info: https://redhat-internal.slack.com/archives/C0218RXJK5E/p1720025910047249
=> Fixing Tempo attribute checks

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml
Change "Content View" and "Composite Content View" to "content view" and "composite content view" to align with updated [RHSSG](https://redhat-documentation.github.io/supplementary-style-guide/#composite-content-view) and [Foreman doc guidelines](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md)
=> Update "Content View", "Composite Content View"

.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc, .vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml
=> Add "Redfish"

.vale/fixtures/RedHat/TermsWarnings/testvalid.adoc, .vale/styles/RedHat/TermsWarnings.yml
Addendum to https://github.com/redhat-documentation/vale-at-red-hat/pull/864
=> tweak like rule

.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml
Allow "Kernel parameters", "Kernel packet filtering", "Kernel arguments"
=> Refine kernel capitalization rule

.vale/fixtures/OpenShiftAsciiDoc/IdHasContextVariable/.vale.ini, .vale/styles/OpenShiftAsciiDoc/IdHasContextVariable.yml
=> value-issue-867: Bumped IdHasContextVariable.yml to error status

modules/user-guide/pages/installing-redhat-style-for-vale.adoc, modules/user-guide/pages/redhat-style-for-vale.adoc
Additional feedback from https://github.com/redhat-documentation/vale-at-red-hat/pull/873/
=> Vale install updates

.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc, .vale/styles/RedHat/CaseSensitiveTerms.yml
Add 'yaml-patch' as an exception to the RH case sensitive rule.
=> Add yaml-patch to case sensitive rule

.vale/fixtures/OpenShiftAsciiDoc/SuggestAttribute/testvalid.adoc, .vale/styles/OpenShiftAsciiDoc/SuggestAttribute.yml
Add "IBM documentation" and "IBM Style" exceptions to `.vale/styles/OpenShiftAsciiDoc/SuggestAttribute.yml`
=> Add "IBM documentation" and "IBM Style" exceptions

.vale/fixtures/RedHat/ObviousTerms/.vale.ini, .vale/fixtures/RedHat/ObviousTerms/testinvalid.adoc, .vale/styles/RedHat/ObviousTerms.yml
Closes https://github.com/redhat-documentation/vale-at-red-hat/issues/889
=> Add ObviousTerms rule

.vale/fixtures/AsciiDoc/ValidConditions/testvalid.adoc, .vale/styles/AsciiDoc/ValidConditions.yml, tengo-rule-scripts/ValidConditions.tengo
Fixes https://github.com/redhat-documentation/vale-at-red-hat/issues/888
=> Fix conditions rule for single line ifdefs

.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc, .vale/styles/RedHat/TermsErrors.yml
=> Add "login to" error

.vale/fixtures/RedHat/SimpleWords/testinvalid.adoc, .vale/styles/RedHat/SimpleWords.yml
Adjusts rule based on https://github.com/redhat-documentation/vale-at-red-hat/issues/921
=> Tweak address

.github/workflows/on-issues-opened.yml, .github/workflows/preview-build.yml, .github/workflows/preview-deploy.yml, .github/workflows/preview-start.yml, .github/workflows/publication-builder.yml, .github/workflows/release.yml, .github/workflows/vale-on-pull.yml, .github/workflows/validate-rules.yml, .github/workflows/validate-scripts.yml, modules/user-guide/pages/using-vale-github-action.adoc
https://nvd.nist.gov/vuln/detail/CVE-2025-30066
=> Freezing actions at current SHA versions in light of CVE-2025-30066

.vale/styles/RedHat/Spelling.yml
Example sentence:
You can configure Persistent Volume Claims (PVCs) and Secrets mount in your {product} deployment.
=> Add PVCs to Spelling.yml

modules/user-guide/pages/adding-vale-configuration-to-a-project.adoc
* Fixing build errors due to broken links.
* Removed Podman Desktop configuration which has been removed.
* Added Eclipse Che and RHDH documentation configuration files.
=> Update sample Vale configuration list
